@url = http://localhost:5000
@reservationId = 00000000-0000-0000-0000-000000000001
@parkingSpotId = 00000000-0000-0000-0000-000000000001
@userId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}

###
GET {{url}}/parking-spots

###
POST {{url}}/parking-spots/{{parkingSpotId}}/reservations/vehicle
Content-Type: application/json

{
    "parkingSpotId": "{{parkingSpotId}}",
    "date": "2022-04-26",
    "licencePlate": "XYZ123",
    "userId": "{{userId}}"
}

###
POST {{url}}/parking-spots/reservations/cleaning
Content-Type: application/json

{
    "date": "2022-05-18"
}


###
PUT {{url}}/parking-spots/reservations/{{reservationId}}
Content-Type: application/json

{
    "licencePlate": "XYZ1234"
}

###
DELETE {{url}}/parking-spots/reservations/{{reservationId}}

###
POST {{url}}/users
Content-Type: application/json

{
    "email": "user1@myspot.io",
    "username": "user1",
    "password": "secret",
    "role": "user",
    "fullName": "John Doe"
}

###
POST {{url}}/users/sign-in
Content-Type: application/json

{
    "email": "user1@myspot.io",
    "password": "secret"
}

###
GET {{url}}/users/secret
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMzQ4NThmNC1lNDdkLTRiMTUtYjQ5OS03Zjc0MmFhODU0ODgiLCJ1bmlxdWVfbmFtZSI6IjEzNDg1OGY0LWU0N2QtNGIxNS1iNDk5LTdmNzQyYWE4NTQ4OCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InVzZXIiLCJuYmYiOjE2NTI3ODg3NDMsImV4cCI6MTY1Mjc5MjM0MywiaXNzIjoibXlzcG90LWlzc3VlciIsImF1ZCI6Im15c3BvdC1hdWRpZW5jZSJ9.FbjR-hwpD9HhnROMhGXA5jiVXOMzvhkfK_tq_L0fyjI